In [18]:
df[df.duplicated()]  # duplicates val.

NameError: name 'df' is not defined

In [ ]:
df = df.drop_duplicates()  # remove the duplicate
df.shape #show rows nums()

(2087, 17)

In [ ]:
df.duplicated().sum() #total num duplicatw= np.int64(0)

np.int64(0)

In [ ]:
#//Check categorical values
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\n, {col}")
    print(df[col].unique())

, Gender
['Female' 'Male']

, family_history_with_overweight
['yes' 'no']

, FAVC
['no' 'yes']

, CAEC
['Sometimes' 'Frequently' 'Always' 'no']

, SMOKE
['no' 'yes']

, SCC
['no' 'yes']

, CALC
['no' 'Sometimes' 'Frequently' 'Always']

, MTRANS
['Public_Transportation' 'Walking' 'Automobile' 'Motorbike' 'Bike']

, NObeyesdad
['Normal_Weight' 'Overweight_Level_I' 'Overweight_Level_II'
 'Obesity_Type_I' 'Insufficient_Weight' 'Obesity_Type_II'
 'Obesity_Type_III']

In [ ]:
#//target variable
df['NObeyesdad'].value_counts()
df['NObeyesdad'].value_counts(normalize=True) * 100

NObeyesdad
Obesity_Type_I         16.818400
Obesity_Type_III       15.524677
Obesity_Type_II        14.230954
Overweight_Level_II    13.895544
Normal_Weight          13.512218
Overweight_Level_I     13.224724
Insufficient_Weight    12.793483
Name: proportion, dtype: float64

In [ ]:
# //Check numerical outliers / IQR Method 
numerical_cols = df.select_dtypes(include='number').columns

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    print(f"\n{col}")
    print("Lower limit:", lower)
    print("Upper limit:", upper)
    print("Outliers:", len(outliers))

Age
Lower limit: 10.789843749999996
Upper limit: 35.12609375
Outliers: 167

Height
Lower limit: 1.421209
Upper limit: 1.978461
Outliers: 1

Weight
Lower limit: 2.976139500000002
Upper limit: 171.03976749999998
Outliers: 1

FCVC
Lower limit: 0.5
Upper limit: 4.5
Outliers: 0

NCP
Lower limit: 2.2436675
Upper limit: 3.4537994999999997
Outliers: 577

CH2O
Lower limit: 0.2780150000000001
Upper limit: 3.779099
Outliers: 0

FAF
Lower limit: -2.2058904999999998
Upper limit: 4.0084975
Outliers: 0

TUE
Lower limit: -1.5
Upper limit: 2.5
Outliers: 0

In [ ]:
# //binary encoding
binary_cols = [
    'family_history_with_overweight',
    'FAVC',
    'SMOKE',
    'SCC'
]

categorical_cols = [
    'Gender',
    'CAEC',
    'CALC',
    'MTRANS'
]

for col in binary_cols:
    df[col] = df[col].map({'yes': 1, 'no': 0})

df[binary_cols].head()

df = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

df.head()

print(df.columns.tolist())

   family_history_with_overweight  FAVC  SMOKE  SCC
0                               1     0      0    0
1                               1     0      1    1
2                               1     0      0    0
3                               0     0      0    0
4                               0     0      0    0

In [ ]:
df = pd.get_dummies(
    df,
    columns=categorical_cols,
    dtype=int
)

df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,...,CAEC_no,CALC_Always,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,21.0,1.62,64.0,1,0,2.0,3.0,0,2.0,0,...,0,0,0,0,1,0,0,0,1,0
1,21.0,1.52,56.0,1,0,3.0,3.0,1,3.0,1,...,0,0,0,1,0,0,0,0,1,0
2,23.0,1.80,77.0,1,0,2.0,3.0,0,2.0,0,...,0,0,1,0,0,0,0,0,1,0
3,27.0,1.80,87.0,0,0,3.0,3.0,0,2.0,0,...,0,0,1,0,0,0,0,0,0,1
4,22.0,1.78,89.8,0,0,2.0,1.0,0,2.0,0,...,0,0,0,1,0,0,0,0,1,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2087 entries, 0 to 2110
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2087 non-null   float64
 1   Height                          2087 non-null   float64
 2   Weight                          2087 non-null   float64
 3   family_history_with_overweight  2087 non-null   int64
 4   FAVC                            2087 non-null   int64
 5   FCVC                            2087 non-null   float64
 6   NCP                             2087 non-null   float64
 7   SMOKE                           2087 non-null   int64
 8   CH2O                            2087 non-null   float64
 9   SCC                             2087 non-null   int64
 10  FAF                             2087 non-null   float64
 11  TUE                             2087 non-null   float64
 12  NObeyesdad                      2087 non-null   object
 13  Gender_Female                   2087 non-null   int64
 14  Gender_Male                     2087 non-null   int64
 15  CAEC_Always                     2087 non-null   int64
 16  CAEC_Frequently                 2087 non-null   int64
 17  CAEC_Sometimes                  2087 non-null   int64
 18  CAEC_no                         2087 non-null   int64
 19  CALC_Always                     2087 non-null   int64
 20  CALC_Frequently                 2087 non-null   int64
 21  CALC_Sometimes                  2087 non-null   int64
 22  CALC_no                         2087 non-null   int64
 23  MTRANS_Automobile               2087 non-null   int64
 24  MTRANS_Bike                     2087 non-null   int64
 25  MTRANS_Motorbike                2087 non-null   int64
 26  MTRANS_Public_Transportation    2087 non-null   int64
 27  MTRANS_Walking                  2087 non-null   int64
dtypes: float64(8), int64(19), object(1)
memory usage: 472.8+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['NObeyesdad'] = label_encoder.fit_transform(df['NObeyesdad'])
df['NObeyesdad'].value_counts()

NObeyesdad
2    351
4    324
3    297
6    290
1    282
5    276
0    267
Name: count, dtype: int64

In [ ]:
X = df.drop('NObeyesdad', axis=1)
y = df['NObeyesdad']

print("Features (X):", X.shape)
print("Target (y):", y.shape)

Features (X): (2087, 27)
Target (y): (2087,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

NameError: name 'X' is not defined

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.preprocessing import StandardScaler

numerical_cols = [
    'Age',
    'Height',
    'Weight',
    'FCVC',
    'NCP',
    'CH2O',
    'FAF',
    'TUE'
]

scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])
X_train[numerical_cols].describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,1.669000e+03,1.669000e+03,1.669000e+03,1.669000e+03,1.669000e+03,1.669000e+03,1.669000e+03,1.669000e+03
mean,-2.022216e-17,3.639988e-15,-2.618237e-16,-4.150864e-16,7.024539e-17,4.496769e-16,1.819994e-16,-1.639059e-16
std,1.000300e+00,1.000300e+00,1.000300e+00,1.000300e+00,1.000300e+00,1.000300e+00,1.000300e+00,1.000300e+00
min,-1.474389e+00,-2.624892e+00,-1.825224e+00,-2.687446e+00,-2.224232e+00,-1.644954e+00,-1.201902e+00,-1.095082e+00
25%,-7.042153e-01,-7.636608e-01,-8.271035e-01,-8.015829e-01,-2.712537e-02,-7.073948e-01,-1.045273e+00,-1.095082e+00
50%,-2.274676e-01,-1.339759e-02,-1.335466e-01,-6.107046e-02,3.918008e-01,-6.556573e-04,-9.637259e-03,-3.140263e-02
75%,2.666902e-01,7.243684e-01,8.124187e-01,1.084280e+00,3.918008e-01,7.413504e-01,7.828870e-01,5.507466e-01
max,5.806486e+00,2.987655e+00,2.821666e+00,1.084280e+00,1.699817e+00,1.643643e+00,2.374891e+00,2.196575e+00

In [ ]:
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

In [ ]:
# df.to_excel("ObesityData_Preprocessed.xlsx", index=False)

# print("Preprocessed dataset saved successfully!")
# print("Shape:", df.shape)

Preprocessed dataset saved successfully!
Shape: (2087, 28)

In [ ]:
#// verify the current df first
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

Shape: (2087, 28)

Columns:
['Age', 'Height', 'Weight', 'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'NObeyesdad', 'Gender_Female', 'Gender_Male', 'CAEC_Always', 'CAEC_Frequently', 'CAEC_Sometimes', 'CAEC_no', 'CALC_Always', 'CALC_Frequently', 'CALC_Sometimes', 'CALC_no', 'MTRANS_Automobile', 'MTRANS_Bike', 'MTRANS_Motorbike', 'MTRANS_Public_Transportation', 'MTRANS_Walking']

Data types:
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight      int64
FAVC                                int64
FCVC                              float64
NCP                               float64
SMOKE                               int64
CH2O                              float64
SCC                                 int64
FAF                               float64
TUE                               float64
NObeyesdad                          int64
Gender_Female                       int64
Gender_Male                         int64
CAEC_Always                         int64
CAEC_Frequently                     int64
CAEC_Sometimes                      int64
CAEC_no                             int64
CALC_Always                         int64
CALC_Frequently                     int64
CALC_Sometimes                      int64
CALC_no                             int64
MTRANS_Automobile                   int64
MTRANS_Bike                         int64
MTRANS_Motorbike                    int64
MTRANS_Public_Transportation        int64
MTRANS_Walking                      int64
dtype: object

Missing values:
0

Duplicates:
0

In [ ]:
print("Shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())

Shape: (2087, 28)
Missing values: 0
Duplicates: 0